services:
  web:
    build:
      context: app
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./app:/project
      - /project/node_modules
    command: ng serve --host 0.0.0.0  
 mongo:
   image: mongo:4.2.8
   ports:
     - 27017:27017
   volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
 volumes:
   mongodb:
   Mongodb_config:
