services:
  web:
    build:
      context: app
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./app:/project
      - /project/node_modules
  back:
    build:
      context: crud-with-mongodb
    ports:
      - 3001:3001
    volumes:
      - ./crud-with-mongodb:/code
  db:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
